<?php
  $lang = array(
    
    //admins.php
    "users-admins" => "Users - Admins",
    "manage"=>"Manage",
    "admins"=>"Admins",
    "add admin" => "Add admin",
    "add new admin" => "Add New Admin",
    "generatereport" => "Generate Report",
    "firstname"=>"First Name",
    "lastname"=>"Last Name",
    "email"=>"Email",
    "telephone"=>"Telephone",
    "password"=>"Password",
    "repeatpassword"=>"Repeat Password",
    "editadmin"=>"Edit Admin",
    "savechanges"=>"Save Changes",
    "deleteadmin"=>"Delete Admin",
    "areyousure"=>"Are you sure you want to delete these Records?",
    "thisaction"=>"This action cannot be undone.",
    //contactus.php
    "contactuslist"=>"Contact Us List",
    "addin"=>"Add in Interest List",
    "subject"=>"Subject",
    "editcustomer"=>"Edit Customer",
    "deletecustomer"=>"Delete Customer",
    "userscustomers"=>"Users - Customers",
    "customers"=>"Customers",
    "addnewcustomer"=>"Add New Customer",
    "addcustomer"=>"Add Customer",
    //messages
    "interestlist"=>"Interest List",
    //newsletter
    "newsletter"=>"Newsletter",
    "sendnewsletter"=>"Send Newsletter",
    "newnewsletter"=>"New Newsletter",
    "deleteuser"=>"Delete User",
    //properties.php
    "properties"=>"Properties",
    "addnewproperty"=>"Add New Property",
    "addnewmultimedia"=>"Add New Multimedia",
    "addpropertydetails"=>"Add Property Details",
    "type"=>"Type",
    "house"=>"House",
    "flat"=>"Flat",
    "category"=>"Category",
    "sale"=>"Sale",
    "longtermrent"=>"Long-Term Rent",
    "shorttermrent"=>"Short-Term Rent",
    "decoration"=>"Decoration",
    "renovation"=>"Renovation",
    "country"=>"Country",
    "city"=>"City",
    "region"=>"Region",
    "address"=>"Address",
    "bedrooms"=>"Bedrooms",
    "bathrooms"=>"Bathrooms",
    "furniture"=>"Furniture",
    "parking"=>"Parking",
    "floor"=>"Floor",
    "heating"=>"Heating",
    "dateofbuild"=>"Year of Build",
    "availablefrom"=>"Available From",
    "squaremeters"=>"Square Meters",
    "pricepersquaremeter"=>"Price Per Square Meter",
    "totalprice"=>"Total Price",
    "description"=>"Description",
    "amenities"=>"Amenities",
    "editpropertydetails"=>"Edit Property Details",
    "type"=>"Type",
    "addpropeprtymultimedia"=>"Add Property Multimedia",
    "photos"=>"Photos(.png, .jpeg)",
    "video"=>"Video(.mp4)",
    "3dphoto"=>"3D Photos(.jpg)",
    "deleteproperty"=>"Delete Property",
    "alltypes"=>"All Types",
    "allcategory"=>"All categories",
    "allcountries"=>"All Countries",
    "allcities"=>"All Cities",
    "allregions"=>"All Regions",
    "renovations"=>"Renovations",
    "addnewrenovation"=>"Add New Renovation",
    "admincustomers"=>"Customers",
    "addrenovation"=>"Add Renovation",
    "property1"=>"Property:",
    "description1"=>"Description:",
    "addrenovationmultimedia"=>"Add RenovationMultimedia",
    "renovation1"=>"Renovation:",
    "photosbefore"=>"Photos Before(.png, .jpeg, .jpg)",
    "photosafter"=>"Photos After(.png, .jpeg, .jpg)",
    "videobefore"=>"Video Before(.mp4)",
    "videoafter"=>"Video After(.mp4)",
    "deleterenovation"=>"Delete Renovation",
    "deletemessagec"=>"Delete Message",
    "deletesubscriber"=>"Delete Subscriber",
    "deleteinteresteduser"=>"Delete Interested",
    "propertiess"=>"Properties",
    //waitinglist
    "manualcontactlist"=>"Manual Contact List",
    "addininterestlist"=>"Add In Interest List",
    //footer+header
    "readytoleave"=>"Ready To Leave?",
    "selectlogout"=>"Select Logout below if you are ready to end your current session.",
    "cancel"=>"Cancel",
    "users"=>"Users",
    "backup"=>"Backup",
    "autobackup"=>"Automatic Backup",
    "autobackupnote"=>"Choose below the interval at which you want the automatic backup to occur.",
    "every"=>"Every","every7"=>"Every 7 days","every30"=>"Every 30 days","every60"=>"Every 60 days","every90"=>"Every 90 days",
    "interval"=>"Current Interval: ","upinterval"=>"Update Interval",
    "backupnote"=>"Pressing 'Backup now' will create a backup of the database for downloading.",
    "restore"=>"Restore",
<<<<<<< Updated upstream
    "note"=>"Note: ",
    "noterestore"=>"Restoring a backup will remove the database that's already in the server.",
=======
    "featuress"=>"Features",
    "adminsss"=>"Admins",
>>>>>>> Stashed changes


    "features"=>"Are you sure you want to delete this administrator",
    "add"=>"Add",
    "delete"=>"Delete",
    "save"=>"Save",
    "send"=>"Send",
    "pleaseselect"=>"Please Select Type",
    "pleaseselectcategory"=>"Please Select Category",
    "pleaseentercountry"=>"Please Enter a Country",
    "pleaseentercity"=>"Please Enter a City",
    "pleaseenterregion"=>"Please Enter a Region",
    "pleaseenteraddress"=>"Please Enter an Address",
    "pleaseselectnumbedrooms"=>"Please Select Number of Bedrooms",
    "pleaseselectnumbathrooms"=>"Please Select Number of Bathrooms",
    "pleaseselectfurniture"=>"Please select if the property has furniture or not",
    "pleaseselectparking"=>"Please select if the property has parking or not",
    "pleaseselectfloor"=>"Please Select Floor",
    "pleaseselectheating"=>"Please select if the property has heating or not",
    "pleaseenteryear"=>"Please enter year of build",
    "pleaseenterdate"=>"Please enter date available from",
    "pleaseentersquare"=>"Please enter square meters",
    "pleaseentersquareprice"=>"Please enter price per square meter",
    "pleaseenterprice"=>"Please enter total price",
    "messages"=>"Messages",
    "navreno" => "Renovations",
    "interestlists"=>"Interest List",  
    "manualcontactlists"=>"Manual Contact List",  
    "contactlistsss"=>"Contact List",

    "website"=>"Website",
    "english"=>"English",
    "greek"=>"Greek",
    "logout"=>"Logout",
    "addpropertymultimedia1"=>"Add Property Multimedia",
    "message"=>"Message",
    "pricepersquare"=>"€/Sqrm",

  

//tables
    "actions"=>"Actions",
    "area"=>"Area",
    "floors"=>"Floor(s)",

    "properties" => "Properties",
    "content" => "Content",
    "edit" => "Edit",
    "displayCarousel" => "Display Carousel",


//Admin and interest list error messages
"entername"=>"Please enter name",
"entersurname"=>"Please enter surname",
"enterphone"=>"Please enter a phone number",
"eightdigits"=>"Please enter at least 8 digits",
"validemail"=>"Please enter a valid email address",
"apassword"=>"Please enter a password",
"sixchars"=>"Please enter at least 6 characters",
"arpassword"=>"Please repeat your password",
"errpassword"=>"Please enter the same password",
"subj"=>"Please enter a subject",
"iframeerror" => "Please enter a location from Google Maps",
"propertydesc" => "Please enter a descritpion",
"propertyamerror" => "Please enter a descritpion for amenities",
"propertycarouselerror" => "Please choose this value",

//Help
"help" => "Help"

  );
