<?php
  $lang = array(
    
    //admins.php
    "users-admins" => "Χρήστες-Διαχειριστές",
    "manage"=>"Διαχείρηση",
    "admins"=>"Διαχειριστές",
    "add admin" => "Προσθήκη Διαχειριστή",
    "add new admin" => "Προσθήκη Νέου Διαχειριστή",
    "generatereport" => "Δημιουργία Αναφοράς",
    "firstname"=>"Όνομα",
    "lastname"=>"Επίθετο",
    "email"=>"Email",
    "telephone"=>"Τηλέφωνο",
    "password"=>"Κωδικός",
    "repeatpassword"=>"Επιβεβαίωση κωδικού",
    "editadmin"=>"Επεξεργασία Διαχειριστή",
    "savechanges"=>"Αποθήκευση Αλλαγών",
    "deleteadmin"=>"Διαγραφή Διαχειριστή",
    "areyousure"=>"Είστε σίγουροι πως θέλετε να διαγράψετε αυτές τις εισαγωγές?",
    "thisaction"=>"Αυτή η πράξη δεν μπορεί να ανερεθεί",
    //contactus.php
    "contactuslist"=>"Λίστα Επικοινωνίας",
    "addin"=>"Προσθήκη στη λίστα Επικοινωνίας",
    "subject"=>"Θέμα",
    "editcustomer"=>"Επεξεργασία Πελάτη",
    "deletecustomer"=>"Διαγραφή Πελάτη",
    "userscustomers"=>"Χρήστες-Πελάτες",
    "customers"=>"Πελάτες",
    "addnewcustomer"=>"Προσθήκη Νέου Πελάτη",
    "addcustomer"=>"Προσθήκη Πελάτη",
    //messages
    "interestlist"=>"Λίστα ενδιαφερομένων",
    //newsletter
    "newsletter"=>"Newsletter",
    "sendnewsletter"=>"Αποστολή Newsletter",
    "newnewsletter"=>"Νέο Newsletter",
    "deleteuser"=>"Διαγραφή Χρήστη",
    //properties.php
    "properties"=>"Ακίνητα",
    "addnewproperty"=>"Προσθήκη Νέου Ακινήτου",
    "addnewmultimedia"=>"Προσθήκη Πολυμέσων",
    "addpropertydetails"=>"Προσθήκη Λεπτομεριών Ακινήτου",
    "type"=>"Τύπος",
    "house"=>"Οικία",
    "flat"=>"Διαμέρισμα",
    "category"=>"Κατηγορία",
    "sale"=>"Πώληση",
    "longtermrent"=>"Μακροχρόνια Ενοικίαση",
    "shorttermrent"=>"Βραχυχρόνια Ενοικίαση",
    "decoration"=>"Διακόσμηση",
    "renovation"=>"Ανακαίνιση",
    "country"=>"Χώρα",
    "city"=>"Πόλη",
    "region"=>"Περιφέρεια",
    "address"=>"Διεύθυνση",
    "bedrooms"=>"Υπνοδωμάτια",
    "bathrooms"=>"Μπάνια",
    "furniture"=>"Επιπλωμένο",
    "parking"=>"Χώρος Στάθμευσης",
    "floor"=>"Όροφος",
    "heating"=>"Θέρμανση",
    "dateofbuild"=>"Χρόνος Κατασκευής",
    "availablefrom"=>"Διαθέσιμο Από",
    "squaremeters"=>"Τετραγωνικά Μέτρα",
    "pricepersquaremeter"=>"Τιμή ανα Τετραγωνικό Μέτρο",
    "totalprice"=>"Συνολική Τιμή",
    "description"=>"Περιγραφή",
    "amenities"=>"Ανέσεις",
    "editpropertydetails"=>"Επεξεργασία Λεπτομερειών Ακινήτου",
    "type"=>"Type",
    "addpropeprtymultimedia"=>"Προσθήκη Πολυμέσων",
    "photos"=>"Φωτογραφίες(.png, .jpeg)",
    "video"=>"Βιντεο(.mp4)",
    "3dphoto"=>"3D Φωτογραφίες(.jpg)",
    "deleteproperty"=>"Διαγραφή Ακινήτου",
    "alltypes"=>"Όλοι οι Τύποι",
    "allcategory"=>"Όλες οι κατηγορίες",
    "allcountries"=>"Όλες οι χώρες",
    "allcities"=>"Όλες οι πόλεις",
    "allregions"=>"Όλες οι περιφέρειες",
    "renovations"=>"Ανακαινίσεων",
    "addnewrenovation"=>"Προσθήκη Νέας Ανακαίνισης",
    "addrenovation"=>"Προσθήκη Ανακαίνισης",
    "property1"=>"Ακίνητο:",
    "description1"=>"Περιγραφή:",
    "addrenovationmultimedia"=>"Προσθήκη Πολυμέσων",
    "renovation1"=>"Ανακαίνηση:",
    "photosbefore"=>"Φωτογραφία Πριν(.png, .jpeg, .jpg)",
    "photosafter"=>"Φωτογραφία Μετά(.png, .jpeg, .jpg)",
    "videobefore"=>"Βίντεο Πριν(.mp4)",
    "videoafter"=>"Βίντεο Μετά(.mp4)",
    "deleterenovation"=>"Διαγραφή Ανακαίνισης",
    //waitinglist
    "manualcontactlist"=>"Χειρ. Λίστα Εποκοινωνίας",
    "addininterestlist"=>"Προσθήκη στη λίστα ενδιαφερομένων",
    //footer+header
    "readytoleave"=>"Αποσύνδεση από τον λογαριασμό;",
    "selectlogout"=>"Επιλέξτε Αποσύνδεση αν θέλετε να αποσυνδεθείτε.",
    "cancel"=>"Ακύρωση",
    "users"=>"Χρήστες",
    "backup"=>"Αντίγραφο Ασφαλείας",
    "restore"=>"Ανάκτηση",


    "features"=>"Είστε σίγουροι πως θέλετε να διαγράψετε τον διαχειριστή;",
    "add"=>"Προσθήκη",
    "delete"=>"Διαγραφή",
    "save"=>"Αποθύκευση",
    "send"=>"Αποστολή",
    "pleaseselect"=>"Παρακαλώ Επιλέξτε Τύπο",
    "pleaseselectcategory"=>"Παρακαλώ Επιλέξτε Κατηγορία",
    "pleaseentercountry"=>"Παρακαλώ Εισάγετε Χώρα",
    "pleaseentercity"=>"Παρακαλώ Εισάγετε Πόλη",
    "pleaseenterregion"=>"Παρακαλώ Εισάγετε Περιφέρεια",
    "pleaseenteraddress"=>"Παρακαλώ Εισάγετε Διεύθυνση",
    "pleaseselectnumbedrooms"=>"Παρακαλώ Επιλέξτε Αριθμό Υπνοδωματίων",
    "pleaseselectnumbathrooms"=>"Παρακαλώ Επιλέξτε Αριθμό Μπάνιων",
    "pleaseselectfurniture"=>"Παρακαλώ επιλέξτε αν το ακίνητο είναι επιπλομένο",
    "pleaseselectparking"=>"Παρακαλώ επιλέξτε αν το ακίνητο διαθέτει χώρο στάθμευσης",
    "pleaseselectfloor"=>"Παρακαλώ επιλέξτε όροφο",
    "pleaseselectheating"=>"Παρακαλώ επιλέξτε αν το ακίνητο διαθέτει θέρμανση",
    "pleaseenteryear"=>"Παρακαλώ εισάγετε χρονολογία κατασκευής ",
    "pleaseenterdate"=>"Παρακαλώ εισάγετε ημερομηνία διαθεσιμότητας",
    "pleaseentersquare"=>"Παρακαλώ εισάγετε αριθμό τετραγωνικών μέτρων",
    "pleaseentersquareprice"=>"Παρακαλώ εισάγετε τιμή για κάθε τετραγωνικό μέτρο",
    "pleaseenterprice"=>"Παρακαλώ εισάγετε συνολική τιμή",
    "messages"=>"Μηνύματα",
    
    "website"=>"Ιστοσελίδα",
    "english"=>"Αγγλικά",
    "greek"=>"Ελληνικά",
    "logout"=>"Αποσύνδεση",
    "addpropertymultimedia1"=>"Προσθήκη Πολυμέσων",
    "message"=>"Μήνυμα",
    "actions"=>"Ενέργειες",
    "pricepersquare"=>"€/Sqrm",

    "area"=>"Περιοχή",
    "floors"=>"Όροφος(οι)",

    "properties" => "Ακίνητα",
    "content" => "Περιεχόμενα",
    "edit" => "Επεξεργασία",




  );
