<?php
  $lang = array(
    
    //admins.php
    "users-admins" => "Χρήστες-Διαχειριστές",
    "manage"=>"Διαχείρηση",
    "admins"=>"Διαχειριστές",
    "add admin" => "Προσθήκη Διαχειριστή",
    "add new admin" => "Προσθήκη Νέου Διαχειριστή",
    "generatereport" => "Δημιουργία Αναφοράς",
    "firstname"=>"Όνομα",
    "lastname"=>"Επίθετο",
    "email"=>"Email",
    "telephone"=>"Τηλέφωνο",
    "password"=>"Κωδικός",
    "repeatpassword"=>"Επιβεβαίωση κωδικού",
    "editadmin"=>"Επεξεργασία Διαχειριστή",
    "savechanges"=>"Αποθήκευση Αλλαγών",
    "deleteadmin"=>"Διαγραφή Διαχειριστή",
    "areyousure"=>"Είστε σίγουροι πως θέλετε να διαγράψετε αυτές τις εισαγωγές?",
    "thisaction"=>"Αυτή η πράξη δεν μπορεί να ανερεθεί",
    //contactus.php
    "contactuslist"=>"Λίστα Επικοινωνίας",
    "addin"=>"Προσθήκη στη λίστα Επικοινωνίας",
    "subject"=>"Θέμα",
    "editcustomer"=>"Επεξεργασία Πελάτη",
    "deletecustomer"=>"Διαγραφή Πελάτη",
    "userscustomers"=>"Χρήστες-Πελάτες",
    "customers"=>"Πελάτες",
    "addnewcustomer"=>"Προσθήκη Νέου Πελάτη",
    "addcustomer"=>"Προσθήκη Πελάτη",
    //messages
    "interestlist"=>"Λίστα ενδιαφερομένων",
    "interestlists"=>"Λίστας ενδιαφερομένων",
    //newsletter
    "newsletter"=>"Newsletter",
    "sendnewsletter"=>"Αποστολή Newsletter",
    "newnewsletter"=>"Νέο Newsletter",
    "deleteuser"=>"Διαγραφή Χρήστη",
    //properties.php
    "properties"=>"Ακίνητα",
    "addnewproperty"=>"Προσθήκη Νέου Ακινήτου",
    "addnewmultimedia"=>"Προσθήκη Πολυμέσων",
    "addpropertydetails"=>"Προσθήκη Λεπτομεριών Ακινήτου",
    "type"=>"Τύπος",
    "house"=>"Οικία",
    "flat"=>"Διαμέρισμα",
    "category"=>"Κατηγορία",
    "sale"=>"Πώληση",
    "longtermrent"=>"Μακροχρόνια Ενοικίαση",
    "shorttermrent"=>"Βραχυχρόνια Ενοικίαση",
    "decoration"=>"Διακόσμηση",
    "renovation"=>"Ανακαίνιση",
    "country"=>"Χώρα",
    "city"=>"Πόλη",
    "region"=>"Περιφέρεια",
    "address"=>"Διεύθυνση",
    "bedrooms"=>"Υπνοδωμάτια",
    "bathrooms"=>"Μπάνια",
    "furniture"=>"Επιπλωμένο",
    "parking"=>"Χώρος Στάθμευσης",
    "floor"=>"Όροφος",
    "heating"=>"Θέρμανση",
    "dateofbuild"=>"Χρόνος Κατασκευής",
    "availablefrom"=>"Διαθέσιμο Από",
    "squaremeters"=>"Τετραγωνικά Μέτρα",
    "pricepersquaremeter"=>"Τιμή ανα Τετραγωνικό Μέτρο",
    "totalprice"=>"Συνολική Τιμή",
    "description"=>"Περιγραφή",
    "amenities"=>"Ανέσεις",
    "editpropertydetails"=>"Επεξεργασία Λεπτομερειών Ακινήτου",
    "type"=>"Type",
    "addpropeprtymultimedia"=>"Προσθήκη Πολυμέσων",
    "photos"=>"Φωτογραφίες(.png, .jpeg)",
    "video"=>"Βιντεο(.mp4)",
    "3dphoto"=>"3D Φωτογραφίες(.jpg)",
    "deleteproperty"=>"Διαγραφή Ακινήτου",
    "alltypes"=>"Όλοι οι Τύποι",
    "allcategory"=>"Όλες οι κατηγορίες",
    "allcountries"=>"Όλες οι χώρες",
    "allcities"=>"Όλες οι πόλεις",
    "allregions"=>"Όλες οι περιφέρειες",
    "renovations"=>"Ανακαινίσεων",
    "addnewrenovation"=>"Προσθήκη Νέας Ανακαίνισης",
    "addrenovation"=>"Προσθήκη Ανακαίνισης",
    "property1"=>"Ακίνητο:",
    "description1"=>"Περιγραφή:",
    "addrenovationmultimedia"=>"Προσθήκη Πολυμέσων",
    "renovation1"=>"Ανακαίνηση:",
    "photosbefore"=>"Φωτογραφία Πριν(.png, .jpeg, .jpg)",
    "photosafter"=>"Φωτογραφία Μετά(.png, .jpeg, .jpg)",
    "videobefore"=>"Βίντεο Πριν(.mp4)",
    "videoafter"=>"Βίντεο Μετά(.mp4)",
    "admincustomers"=>"Πελατών",
    "deleterenovation"=>"Διαγραφή Ανακαίνισης",
    "deletemessagec"=>"Διαγραφή Μηνύματος",
    "deletemessagec"=>"Διαγραφή Μηνύματος",
    "deletesubscriber"=>"Διαγραφή Συνδρομητή",
    "deleteinteresteduser"=>"Διαγραφή ενδιαφερομένου",
    //waitinglist
    "manualcontactlist"=>"Χειρ. Λίστα Επικοινωνίας",
    "manualcontactlists"=>"Χειρ. Λίστας Επικοινωνίας",
    "addininterestlist"=>"Προσθήκη στη λίστα ενδιαφερομένων",
    //footer+header
    "readytoleave"=>"Αποσύνδεση από τον λογαριασμό;",
    "selectlogout"=>"Επιλέξτε Αποσύνδεση αν θέλετε να αποσυνδεθείτε.",
    "cancel"=>"Ακύρωση",
    "users"=>"Χρήστες",
    "backup"=>"Αντίγραφο Ασφαλείας",
    "restore"=>"Ανάκτηση",
<<<<<<< Updated upstream
    "autobackup"=>"Αυτόματο Αντίγραφο Ασφαλείας",
    "autobackupnote"=>"Διαλέξετε πιο κάτω πόσο συχνά θέλετε να δημιουργήτε ένα αντίγραφο ασφαλείας.",
    "every"=>"Κάθε","every7"=>"Κάθε 7 μέρες","every30"=>"Κάθε 30 μέρες","every60"=>"Κάθε 60 μέρες","every90"=>"Κάθε 90 μέρες",
    "interval"=>"Παρούσα Συχνότητα: ","upinterval"=>"Ανανέωση Συχνότητας",
    "backupnote"=>"Πατώντας 'Αντίγραφο Ασφαλείας' θα δημιουργηθεί ένα αντίγραφο ασφαλείας για κατέβασμα.",
    "restore"=>"Ανάκτηση",
    "note"=>"Σημείωση: ",
    "noterestore"=>"Η ανάκτηση ενός αντίγραφου ασφαλείας θα διαγράψει την παρούσα βάση δεδομέων.",

=======
    "propertiess"=>"Ακινήτων",
    "adminsss"=>"Διαχειριστών",
    "contactlistsss"=>"Λίστας Επικοινωνίας",
>>>>>>> Stashed changes

    "features"=>"Είστε σίγουροι πως θέλετε να διαγράψετε τον διαχειριστή;",
    "featuress"=>"Features",
    "add"=>"Προσθήκη",
    "delete"=>"Διαγραφή",
    "save"=>"Αποθήκευση",
    "send"=>"Αποστολή",
    "pleaseselect"=>"Παρακαλώ Επιλέξτε Τύπο",
    "pleaseselectcategory"=>"Παρακαλώ Επιλέξτε Κατηγορία",
    "pleaseentercountry"=>"Παρακαλώ Εισάγετε Χώρα",
    "pleaseentercity"=>"Παρακαλώ Εισάγετε Πόλη",
    "pleaseenterregion"=>"Παρακαλώ Εισάγετε Περιφέρεια",
    "pleaseenteraddress"=>"Παρακαλώ Εισάγετε Διεύθυνση",
    "pleaseselectnumbedrooms"=>"Παρακαλώ Επιλέξτε Αριθμό Υπνοδωματίων",
    "pleaseselectnumbathrooms"=>"Παρακαλώ Επιλέξτε Αριθμό Μπάνιων",
    "pleaseselectfurniture"=>"Παρακαλώ επιλέξτε αν το ακίνητο είναι επιπλομένο",
    "pleaseselectparking"=>"Παρακαλώ επιλέξτε αν το ακίνητο διαθέτει χώρο στάθμευσης",
    "pleaseselectfloor"=>"Παρακαλώ επιλέξτε όροφο",
    "pleaseselectheating"=>"Παρακαλώ επιλέξτε αν το ακίνητο διαθέτει θέρμανση",
    "pleaseenteryear"=>"Παρακαλώ εισάγετε χρονολογία κατασκευής ",
    "pleaseenterdate"=>"Παρακαλώ εισάγετε ημερομηνία διαθεσιμότητας",
    "pleaseentersquare"=>"Παρακαλώ εισάγετε αριθμό τετραγωνικών μέτρων",
    "pleaseentersquareprice"=>"Παρακαλώ εισάγετε τιμή για κάθε τετραγωνικό μέτρο",
    "pleaseenterprice"=>"Παρακαλώ εισάγετε συνολική τιμή",
    "messages"=>"Μηνύματα",
    "navreno" => "Ανακαινίσεις",

    
    "website"=>"Ιστοσελίδα",
    "english"=>"Αγγλικά",
    "greek"=>"Ελληνικά",
    "logout"=>"Αποσύνδεση",
    "addpropertymultimedia1"=>"Προσθήκη Πολυμέσων",
    "message"=>"Μήνυμα",
    "actions"=>"Ενέργειες",
    "pricepersquare"=>"€/Sqrm",

    "area"=>"Περιοχή",
    "floors"=>"Όροφος(οι)",

    "properties" => "Ακίνητα",
    "content" => "Περιεχόμενα",
    "edit" => "Επεξεργασία",
    "displayCarousel" => "Προβολή στο Carousel",

    

  //Admin error messages
"entername"=>"Παρακαλώ εισάγετε ένα όνομα",
"entersurname"=>"Παρακαλώ εισάγετε ένα επώνυμο",
"enterphone"=>"Παρακαλώ εισάγετε ένα αριθμό τηλεφώνου",
"eightdigits"=>"Παρακαλώ εισάγετε τουλάχιστον 8 ψηφία",
"validemail"=>"Παρακαλώ εισάγετε ένα έγκυρο email",
"apassword"=>"Παρακαλώ εισάγετε ένα κωδικό",
"sixchars"=>"Παρακαλώ εισάγετε τουλάχιστον 6 χαρακτήρες",
"arpassword"=>"Παρακαλώ επαναλάβετε τον κωδικό σας",
"errpassword"=>"Παρακαλώ εισάγετε τον ίδιο κωδικό",
"subj"=>"Παρακαλώ εισάγετε ένα θέμα",
"iframeerror" => "Παρακαλώ επιλέξτε ένα iframe από το Google Maps",
"propertydesc" => "Παρακαλώ εισάγετε μία περιγραφή",
"propertyamerror" => "Παρακαλώ εισάγετε μια περιγραφή γιά τις ανέσεις",
"propertycarouselerror" => "Παρακαλώ εισάγετε μιά επιλογή",

//Help
"help" => "Βοήθεια"

  );
